name: qw_cli
description: Cross-platform enhanced CLI tools for your daily needs
version: 1.0.1
homepage: https://github.com/andypangaribuan/qw-cli

environment:
  sdk: '>=2.17.6 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  dcli: ^1.33.0
  yaml: ^3.1.1

  dtg: ^1.0.1
  # dtg:
    # path: /Users/apangaribuan/repo/github/dtg
