name: qw_cli
description: A simple command-line application.
version: 1.0.0
homepage: https://github.com/andypangaribuan

environment:
  sdk: '>=2.17.0 <3.0.0'

dev_dependencies:
  dcli: ^1.33.0
  yaml: ^3.1.1
  lints: ^2.0.0
