apiVersion: v1
kind: Pod
metadata:
  name: xcurl
spec:
  containers:
    - name: xcurl
      image: radial/busyboxplus:curl
      imagePullPolicy: Always
      resources:
        requests:
          cpu: 50
          memory: 100
          ephemeral-storage: 50
        limits:
          memory: 100
          ephemeral-storage: 50
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
